"""Fuck this

Revision ID: a7f86acb5e5c
Revises: 
Create Date: 2024-01-16 21:45:21.233000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a7f86acb5e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('password_hash', sa.String(length=200), nullable=True),
                    sa.Column('last_name', sa.String(length=100), nullable=True),
                    sa.Column('drug_testing_phone', sa.String(length=20), nullable=True),
                    sa.Column('ivr_code', sa.String(length=20), nullable=True),
                    sa.Column('mobile_number1', sa.String(length=20), nullable=True),
                    sa.Column('mobile_number2', sa.String(length=20), nullable=True),
                    sa.Column('checkin_time', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
