"""updated routes, models

Revision ID: e3b3ff83ee53
Revises: a7f86acb5e5c
Create Date: 2024-01-17 04:15:23.016615

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e3b3ff83ee53'
down_revision = 'a7f86acb5e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_of_week', sa.String(length=255), nullable=True))
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=False)
        batch_op.alter_column('checkin_time',
                              existing_type=sa.DATETIME(),
                              type_=sa.Time(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('checkin_time',
                              existing_type=sa.Time(),
                              type_=sa.DATETIME(),
                              existing_nullable=True)
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True)
        batch_op.drop_column('days_of_week')

    # ### end Alembic commands ###
